name = "booking-worker"
account_id = "a0c5e93c44c4e217f2b167fd0beb4b39"
main = "worker/src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
OWNER_NAME = "Nils Eckelt"
OWNER_EMAIL = "nils@ecke.lt"
CALDAV_CALENDAR_NILS = "bd0ce304-f055-4524-9273-80a7d8cee9f1"
CALDAV_CALENDAR_OHANA = "0C692FAB-66C9-454F-B51D-D076560588DB"

[[routes]]
pattern = "book.ecke.lt/api/*"
zone_name = "ecke.lt"
